
# ------------------------------
# 模型权重载入两种规则
# 1. 训练模式，只载入 encoder 的权重
# 2. 推理模式，载入 所有的权重
#
# 具体配置的时候，看是否存在 ckpt_path 路径中的文件是否存在，则切换为推理模式

ckpt_path: Null  
encoder_path: 'checkpoints/encoder[first_31_layers_vgg].pth'
